

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_PARENT_ID, PRODUCT_NAME,PRODUCT_DESC,PRODUCT_PRICE,PRODUCT_CREATED_TS,PRODUCT_UPDATED_TS)
VALUES (1,null,'Apple Iphone','Apple Smartphones', 0.0,CURRENT_DATE(),CURRENT_DATE());

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_PARENT_ID, PRODUCT_NAME,PRODUCT_DESC,PRODUCT_PRICE,PRODUCT_CREATED_TS,PRODUCT_UPDATED_TS)
VALUES (2,1,'Apple Iphone 5','Apple Smartphone version 5', 1000.500,CURRENT_DATE(),CURRENT_DATE());

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_PARENT_ID, PRODUCT_NAME,PRODUCT_DESC,PRODUCT_PRICE,PRODUCT_CREATED_TS,PRODUCT_UPDATED_TS)
VALUES (3,1,'Apple Iphone 6','Apple Smartphone version 6', 2000.200,CURRENT_DATE(),CURRENT_DATE());

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_PARENT_ID, PRODUCT_NAME,PRODUCT_DESC,PRODUCT_PRICE,PRODUCT_CREATED_TS,PRODUCT_UPDATED_TS)
VALUES (4,null,'Sumsung smartphone','Sumsung Smartphones', 0.0,CURRENT_DATE(),CURRENT_DATE());

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_PARENT_ID, PRODUCT_NAME,PRODUCT_DESC,PRODUCT_PRICE,PRODUCT_CREATED_TS,PRODUCT_UPDATED_TS)
VALUES (5,4,'Sumsung Galaxy 1','Sumsung Galaxy 1', 600.0,CURRENT_DATE(),CURRENT_DATE());

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_PARENT_ID, PRODUCT_NAME,PRODUCT_DESC,PRODUCT_PRICE,PRODUCT_CREATED_TS,PRODUCT_UPDATED_TS)
VALUES (6,4,'Sumsung Galaxy 2','Sumsung Galaxy 2', 900.0,CURRENT_DATE(),CURRENT_DATE());


INSERT INTO USER (USER_ID, USER_NAME, USER_PASSWORD,USER_EMAIL,USER_ROLES,USER_CREATED_TS,USER_UPDATED_TS)
VALUES (1,'ERIK','$2a$10$D4OLKI6yy68crm.3imC9X.P2xqKHs5TloWUcr6z5XdOqnTrAK84r','ROLE_USER','erikpalves@hotmail.com', CURRENT_DATE(),CURRENT_DATE());

INSERT INTO USER (USER_ID, USER_NAME, USER_PASSWORD,USER_EMAIL,USER_ROLES,USER_CREATED_TS,USER_UPDATED_TS)
VALUES (2,'ALVES','$2a$10$D4OLKI6yy68crm.3imC9X.P2xqKHs5TloWUcr6z5XdOqnTrAK84r','ROLE_USER,ROLE_ADMIN','erikpalves@hotmail.com', CURRENT_DATE(),CURRENT_DATE());
