
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS USER;

CREATE TABLE PRODUCT
(
	PRODUCT_ID IDENTITY PRIMARY KEY,
	PRODUCT_PARENT_ID NUMBER(19) NULL,
	PRODUCT_NAME VARCHAR2(50) NOT NULL,
	PRODUCT_DESC VARCHAR2(200) NOT NULL,
	PRODUCT_PRICE NUMBER(19) NOT NULL,
	PRODUCT_CREATED_TS DATE NOT NULL,
	PRODUCT_UPDATED_TS DATE NOT NULL,
);


CREATE TABLE USER
(
	USER_ID IDENTITY PRIMARY KEY,
	USER_NAME VARCHAR2(50) NOT NULL,
	USER_PASSWORD VARCHAR2(200) NOT NULL,
	USER_EMAIL VARCHAR2(200) NOT NULL,
	USER_ROLES VARCHAR2(200) NOT NULL,
	USER_CREATED_TS DATE NOT NULL,
	USER_UPDATED_TS DATE NOT NULL,
);
