
DROP TABLE IF EXISTS PRODUCT;


CREATE TABLE PRODUCT
(
	PRODUCT_ID IDENTITY PRIMARY KEY,
	PRODUCT_PARENT_ID NUMBER(19) NULL,
	PRODUCT_NAME VARCHAR2(50) NOT NULL,
	PRODUCT_DESC VARCHAR2(200) NOT NULL,
	PRODUCT_PRICE NUMBER(19) NOT NULL,
	PRODUCT_CREATED_TS TIMESTAMP NOT NULL,
	PRODUCT_UPDATED_TS TIMESTAMP NOT NULL,
);
